# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Ubuntu
  config.vm.box = "utm/ubuntu-24.04"

  # Forward ports so we can test that FusionAuth is running
  config.vm.network "forwarded_port", guest: 9011, host: 9011, host_ip: "127.0.0.1"

  # Bump RAM and CPU
  config.vm.provider "utm" do |vb|
    vb.check_guest_additions = false
    vb.cpus = 4
    vb.memory = "4096"
  end

  # Execute the local install script
  config.vm.provision "shell", inline: <<-SHELL
    VERSION=$(curl -fsSL https://license.fusionauth.io/api/latest-version)
    curl -fsSL https://files.fusionauth.io/products/fusionauth/${VERSION}/fusionauth-search_${VERSION}-1_all.deb > fusionauth-search_${VERSION}-1_all.deb
    curl -fsSL https://files.fusionauth.io/products/fusionauth/${VERSION}/fusionauth-app_${VERSION}-1_all.deb > fusionauth-app_${VERSION}-1_all.deb
    dpkg -i fusionauth-search_${VERSION}-1_all.deb
    dpkg -i fusionauth-app_${VERSION}-1_all.deb
    service fusionauth-search start
    service fusionauth-app start
  SHELL
end
