# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Ubuntu
  config.vm.box = "utm/ubuntu-24.04"

  # Forward ports so we can test that FusionAuth is running
  config.vm.network "forwarded_port", guest: 9011, host: 9011, host_ip: "127.0.0.1"

  # Bump RAM and CPU
  config.vm.provider "utm" do |vb|
    vb.check_guest_additions = false
    vb.cpus = 4
    vb.memory = "4096"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "file", source: "install.sh", destination: "install.sh"

  # Execute the local install script
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt install -y unzip
    ./install.sh -s
    ./fusionauth/bin/startup.sh
  SHELL
end
